### ISSUE TITLE
services.AddRepositories is confusing

### ISSUE THREAD

**Issue by stijwilliams** [NephosIntegration/Formula.SimpleRepo#3]
Currently only have to target adding repositories within a specific assembly, by getting the "typeof" from one example repository, but this is confusing.. Leading developers to add each repository when they don't have too.

Example..
services.AddRepositories(typeof(STI.HostAccess.Core.Data.HostAccessRepository));

Should be something liek
services.AddRepositories(assemblyreference);

**Comment by brentconey** [comment]
I've added a PR to address this.

**Comment by brentconey** [comment]
https://github.com/NephosIntegration/Formula.SimpleRepo/pull/8

**Comment by joshua-p-williams** [comment]
Will be available in 1.1.*
